### ISSUE TITLE
Latest release is currently broken / jsxlate-loader no longer functioning

### ISSUE THREAD

**Issue by stevenp** [drd/jsxlate#7] opened 2016-03-11 02:12 UTC
I'm trying to integrate this component into my project, along with jsxlate-loader, and I've run into a few issues:

index.js has several invalid imports:

```
var translator = require('./lib/jsxlate');
var components = require('./lib/components.jsx');
var cache = require('./lib/cache.js');
```

The lib directory isn't present because the build.sh script isn't currently working. It looks like it creates the directory, but then puts the files into ./build instead. Even with changing the path, the first file doesn't exist anymore.

Looking at jsxlate-loader, it seems like it still relies on the 0.3.x release. Should I just not use the latest release that's been published?

**Comment by stevenp** [comment] 2016-03-11 05:14
I spent a few hours working on this and I was able to get things working with the older versions, though it took some finagling because Webpack wasn't too happy about the way imports were structured in the examples (they were including node-only modules). 

I'm really excited to use your library at my company, and I'd love to get a sense of what the future of the project is, or whether it would make more sense for me to fork the older version. I'm using it to provide translations for an isomorphic React app and there are currently quite a few hurdles to getting it integrated. I'd love to help in any way I can.

**Comment by drd** [comment] 2016-03-11 06:01
Sorry for the ham-fisted release. I didn't think anyone was actively using it or I would have been a bit more careful... 😅

So, jsxlate 0.4+ is now based on Babel 6 and does not require jsxlate-loader. To use jsxlate you simply list it in your `.babelrc` plugins list. I intend to have some examples up soon. If you're still using Babel 5 I would recommend pinning to the old version. 

If you let me know what integration difficulties you're having I'd be happy to help address them as best I can. We have been using jsxlate in production for several months without issue, in an isomorphic app as well, at idealist. 

Sorry again for costing you so much time — I'm thrilled you're interested in the project!

**Comment by drd** [comment] 2016-03-11 06:02
Oh, meant to mention: `index.js` obviously needs an update. I should have a new version out tomorrow.

**Comment by stevenp** [comment] 2016-03-11 06:32
@drd Thanks for the quick reply! It's actually been a fun challenge getting up and running, so no worries at all. I actually just realized that I could add it to .babelrc once I read through the src README, did that, and it's working like a charm. 

Here's another issue I ran into: babel-polyfill isn't included in any of the build files, and as a result my Webpack compilation will only work if I require it in the config file. What are the odds that you might be able to automatically include it since it's already a package dependency? I'm not sure if there's another better approach to this, but because it's not present, Webpack fails on a few calls to `Object.entries` and trying to call `toJSON()` on a set.

**Comment by stevenp** [comment] 2016-03-11 07:05
Just a little more context... even when running Babel from the command line, I get the same error:

```
$(npm bin)/babel app/shared/apps/repair/components/ColorsContainer/ColorsContainer.js
TypeError: app/shared/apps/repair/components/ColorsContainer/ColorsContainer.js: variables.toJSON is not a function
    at freeVariablesInMessage (/Users/steven/dev/icr-front-end/node_modules/jsxlate/build/free-variables.js:23:22)
    at Object.transformElementMarker (/Users/steven/dev/icr-front-end/node_modules/jsxlate/build/transformation.js:38:48)
    at PluginPass.enter (/Users/steven/dev/icr-front-end/node_modules/jsxlate/build/transform.js:19:67)
    at newFn (/Users/steven/dev/icr-front-end/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:262:19)
    at NodePath._call (/Users/steven/dev/icr-front-end/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:63:18)
    at NodePath.call (/Users/steven/dev/icr-front-end/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:47:17)
    at NodePath.visit (/Users/steven/dev/icr-front-end/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:93:12)
    at TraversalContext.visitQueue (/Users/steven/dev/icr-front-end/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:146:16)
    at TraversalContext.visitMultiple (/Users/steven/dev/icr-front-end/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:110:17)
    at TraversalContext.visit (/Users/steven/dev/icr-front-end/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:176:19)
```

For reference, here's my .babelrc:

```
{
 "presets": [ "react", "es2015" ],
 "plugins": [ "jsxlate" ]
}
```

I did a little searching, and it looks there isn't a preset that includes `Object.entries` or `map/set.toJSON`yet.

**Comment by drd** [comment] 2016-03-11 17:45
Yes, that is something that must be included using `babel-polyfill`, which should not be `require()` by a library — only one instance of it can be active at a time, so it is your app's responsibility to include it. It should be marked as a `peerDependency` and documented. Thanks for pointing this out!

**Comment by stevenp** [comment] 2016-03-11 17:56
Thanks, Eric! I'm happy to add `babel-polyfill` as a `peerDependency` in a PR and update the documentation as well, if you'd like. Just let me know. Feel free to close this whenever you'd like.

**Comment by drd** [comment] 2016-03-11 17:58
Yes, that would be awesome. I just pushed some updates that attempt to clarify the situation, but I didn't add the peerDep, if you could that would be awesome!

**Comment by stevenp** [comment] 2016-03-11 18:47
I'm happy to do this, but how would you explain in the README what people would need to do to run babel-cli using the jsxlate plugin? Does babel automatically import babel-polyfill when running it using the CLI? Otherwise, I'm not sure how you would get it to work.

**Comment by drd** [comment] 2016-03-11 21:05
I think the only thing you need to do is have `require('babel-polyfill')` in the entrypoint of your app. This will probably be true for tests as well. We have it in server, client, and test entrypoints. I'm not sure of a better way to handle this.

**Comment by stevenp** [comment] 2016-03-11 21:22
Got it, but my concern is that your local jsxlate tests won't pass if `babel-polyfill` isn't a hard dependency. I'll give it a shot and see what happens.

**Comment by drd** [comment] 2016-03-11 21:26
Ha, apparently it already is: https://github.com/drd/jsxlate/commit/9a258c5cbe041d62917a487814bd0983d9ed7bdd

And it's required in test/test-extraction.js...

**Comment by stevenp** [comment] 2016-03-11 21:34
That's why I was asking if you really want to move it to `peerDependencies`. I'm guessing you really just want to add it, not move it, which I'm happy to do, but I'm not sure what it buys, since any project including the library is guaranteed to have `babel-polyfill` as a result of you including it, no?

**Comment by drd** [comment] 2016-03-11 21:36
Ohhh ha ha. Honestly I'm not even sure what the best thing to do is until everyone is on npm v3. I guess let's leave it as a hard dependency and just mention it in the docs that it's required to be added to the entrypoints of your app.

**Comment by drd** [comment] 2016-03-11 21:37
The problem is that if I include `babel-polyfill` in the library code, and someone else's app is already including `babel-polyfill`, then it will error. See https://github.com/babel/babel/blob/master/packages/babel-polyfill/src/index.js#L3

**Comment by stevenp** [comment] 2016-03-11 21:54
That's odd -- I was including it but didn't run into this problem. But maybe that's because I'm using npm 3 and the versions match? This makes my head hurt. Haha

**Comment by aleksey-shmatov** [comment] 2016-04-04 03:42
I have run into the same issue. According to this: https://github.com/DavidBruant/Map-Set.prototype.toJSON/issues/16 toJSON for Set and Map is rejected so it would be better to use something else for serialization.

**Comment by drd** [comment] 2016-04-28 05:20
@aleksey-shmatov thanks for the heads up about `toJSON`. I have switched to using an Object as the set. @stevenp I have completely removed jsxlate's dependency on `babel-polyfill` so hopefully that will help! Sorry this took so long, I just started a new job … and we don't use jsxlate (yet!). Let me know if 0.6.0 resolves your issues.

**Closed as completed** 2016-04-28 05:20 UTC
